name: "Unit Tests"

# Run on any PR and pushes to main
on:
  pull_request:
  push:
    branches:
    - "main"
    
  workflow_dispatch:
    
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest
    - run: mkdir build
    - name: Run Tests
      run: |
        cd build
        cmake ../gesturelibrary
        make
        ctest --verbose
